-- MySQL Script generated by MySQL Workbench
-- Sat May 22 10:32:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema centroOdontologico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centroOdontologico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centroOdontologico` DEFAULT CHARACTER SET latin1 ;
USE `centroOdontologico` ;

-- -----------------------------------------------------
-- Table `centroOdontologico`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centroOdontologico`.`Paciente` (
  `idPaciente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `numeroDocumento` BIGINT UNSIGNED NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `correoElectronico` VARCHAR(60) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idPaciente`),
  UNIQUE INDEX `NUMERO DE DOCUMENTO_UNIQUE` (`numeroDocumento` ASC),
  UNIQUE INDEX `CORREO ELECTRONICO_UNIQUE` (`correoElectronico` ASC),
  UNIQUE INDEX `idPACIENTE_UNIQUE` (`idPaciente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centroOdontologico`.`Odontologo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centroOdontologico`.`Odontologo` (
  `idOdontologo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `numDocumento` BIGINT NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `tiempoExperiencia` SMALLINT UNSIGNED NOT NULL,
  `salario` DOUBLE(9,2) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`idOdontologo`),
  UNIQUE INDEX `CORREO ELECTRONICO_UNIQUE` (`email` ASC),
  UNIQUE INDEX `NUMERO DE DOCUMENTO_UNIQUE` (`numDocumento` ASC),
  UNIQUE INDEX `idOdontologo_UNIQUE` (`idOdontologo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centroOdontologico`.`Consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centroOdontologico`.`Consultorio` (
  `idConsultorio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` SMALLINT UNSIGNED NOT NULL,
  `piso` SMALLINT UNSIGNED NOT NULL,
  `disponibilidad` ENUM('Ocupado', 'Libre', 'Mantenimiento') NOT NULL,
  PRIMARY KEY (`idConsultorio`),
  UNIQUE INDEX `idCONSULTORIO_UNIQUE` (`idConsultorio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centroOdontologico`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centroOdontologico`.`Cita` (
  `idCita` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `tratamiento` TEXT NOT NULL,
  `consultorioId` INT UNSIGNED NOT NULL,
  `odontologoId` INT UNSIGNED NOT NULL,
  `pacienteId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCita`),
  UNIQUE INDEX `idCITAS_UNIQUE` (`idCita` ASC),
  INDEX `fk_CITAS_CONSULTORIO_idx` (`consultorioId` ASC),
  INDEX `fk_CITAS_ODONTOLOGOS1_idx` (`odontologoId` ASC),
  INDEX `fk_CITAS_PACIENTE1_idx` (`pacienteId` ASC),
  CONSTRAINT `fk_CITAS_CONSULTORIO`
    FOREIGN KEY (`consultorioId`)
    REFERENCES `centroOdontologico`.`Consultorio` (`idConsultorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITAS_ODONTOLOGOS1`
    FOREIGN KEY (`odontologoId`)
    REFERENCES `centroOdontologico`.`Odontologo` (`idOdontologo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITAS_PACIENTE1`
    FOREIGN KEY (`pacienteId`)
    REFERENCES `centroOdontologico`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
