/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import Clases.*;import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
;

/**
 *
 * @author Kisuke
 */
public class frmConsultorios extends javax.swing.JFrame {

    
    int idTempo, idTempoEliminar;
    
    /**
     * Creates new form frmOdontologos
     */
    public frmConsultorios() {
        initComponents();
        jPanel_Edit_Consultorio.setVisible(false);
        ListarConsultorios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPnl_Nuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLbl_Descripcion = new javax.swing.JLabel();
        jLbl_Numero = new javax.swing.JLabel();
        jLbl_Piso = new javax.swing.JLabel();
        jLbl_Disponibilidad = new javax.swing.JLabel();
        jBtn_Guardar = new javax.swing.JButton();
        jBtn_Cancelar = new javax.swing.JButton();
        jftxtf_Numero = new javax.swing.JFormattedTextField();
        jSpn_Piso = new javax.swing.JSpinner();
        jSpn_Estado = new javax.swing.JSpinner();
        jPnl_Editar = new javax.swing.JPanel();
        jPanel_Edit_Consultorio = new javax.swing.JPanel();
        jLbl_edit_Numero = new javax.swing.JLabel();
        jLbl_edit_Piso = new javax.swing.JLabel();
        jLbl_edit_Disponibilidad = new javax.swing.JLabel();
        jBtn_Guardar1 = new javax.swing.JButton();
        jLbl_edit_Icon = new javax.swing.JLabel();
        jBtn_Cancelar1 = new javax.swing.JButton();
        jftxtf_edit_Numero = new javax.swing.JFormattedTextField();
        jSpn_edit_Piso = new javax.swing.JSpinner();
        jSpn_edit_Estado = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLbl_buscar_Consultorio = new javax.swing.JLabel();
        jcbx_Editar_Consultorio = new javax.swing.JComboBox();
        jPnl_Buscar = new javax.swing.JPanel();
        jPnlBusq_Basica = new javax.swing.JPanel();
        jTxt_Busqueda_Basica = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jcb_Buscar_Campo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Buscar = new javax.swing.JTable();
        jPnl_Listar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPnl_Eliminar = new javax.swing.JPanel();
        jPnEliminar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCbx_Eliminar_Consultorio = new javax.swing.JComboBox();
        jPanel_Deleted_Consultorio = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTxtf_Numero_Eliminar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtf_Piso_Eliminar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtf_Disponibilidad_Eliminar = new javax.swing.JTextField();
        jBtn_Eliminar = new javax.swing.JButton();
        jBtn_Cancelar_Eliminar = new javax.swing.JButton();
        jmenu_principal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMPrincipal = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Consultorios");

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Consultorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLbl_Descripcion.setText("Por favor ingrese los datos del consultorio");

        jLbl_Numero.setText("Numero");

        jLbl_Piso.setText("Piso");

        jLbl_Disponibilidad.setText("Disponibilidad");

        jBtn_Guardar.setText("Guardar");
        jBtn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_GuardarActionPerformed(evt);
            }
        });

        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jftxtf_Numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jSpn_Piso.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        jSpn_Estado.setModel(new javax.swing.SpinnerListModel(new String[] {"Ocupada", "Libre", "Mantenimiento"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLbl_Disponibilidad)
                                    .addComponent(jLbl_Piso)
                                    .addComponent(jLbl_Numero))
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtn_Cancelar)
                                .addGap(17, 17, 17)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpn_Piso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_Guardar)
                            .addComponent(jSpn_Estado, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jftxtf_Numero))
                        .addGap(215, 215, 215)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLbl_Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Numero)
                    .addComponent(jftxtf_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Piso)
                    .addComponent(jSpn_Piso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Disponibilidad)
                    .addComponent(jSpn_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Cancelar)
                    .addComponent(jBtn_Guardar))
                .addGap(270, 270, 270))
        );

        javax.swing.GroupLayout jPnl_NuevoLayout = new javax.swing.GroupLayout(jPnl_Nuevo);
        jPnl_Nuevo.setLayout(jPnl_NuevoLayout);
        jPnl_NuevoLayout.setHorizontalGroup(
            jPnl_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_NuevoLayout.setVerticalGroup(
            jPnl_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nuevo", jPnl_Nuevo);

        jPnl_Editar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPnl_EditarFocusGained(evt);
            }
        });

        jPanel_Edit_Consultorio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Consultorio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLbl_edit_Numero.setText("Numero");

        jLbl_edit_Piso.setText("Piso");

        jLbl_edit_Disponibilidad.setText("Disponibilidad");

        jBtn_Guardar1.setText("Guardar");
        jBtn_Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Guardar1ActionPerformed(evt);
            }
        });

        jLbl_edit_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/Edit-Male-User-icon.png"))); // NOI18N

        jBtn_Cancelar1.setText("Cancelar");
        jBtn_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Cancelar1ActionPerformed(evt);
            }
        });

        jftxtf_edit_Numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###"))));

        jSpn_edit_Piso.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        jSpn_edit_Estado.setModel(new javax.swing.SpinnerListModel(new String[] {"Ocupada", "Libre", "Mantenimiento"}));

        javax.swing.GroupLayout jPanel_Edit_ConsultorioLayout = new javax.swing.GroupLayout(jPanel_Edit_Consultorio);
        jPanel_Edit_Consultorio.setLayout(jPanel_Edit_ConsultorioLayout);
        jPanel_Edit_ConsultorioLayout.setHorizontalGroup(
            jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_ConsultorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Edit_ConsultorioLayout.createSequentialGroup()
                        .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl_edit_Numero)
                            .addComponent(jLbl_edit_Disponibilidad)
                            .addComponent(jLbl_edit_Piso))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Edit_ConsultorioLayout.createSequentialGroup()
                                .addComponent(jSpn_edit_Piso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jftxtf_edit_Numero)
                            .addComponent(jSpn_edit_Estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
                    .addGroup(jPanel_Edit_ConsultorioLayout.createSequentialGroup()
                        .addComponent(jBtn_Cancelar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_Guardar1)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbl_edit_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel_Edit_ConsultorioLayout.setVerticalGroup(
            jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_ConsultorioLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_Edit_ConsultorioLayout.createSequentialGroup()
                        .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_edit_Numero)
                            .addComponent(jftxtf_edit_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpn_edit_Piso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_edit_Piso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_edit_Disponibilidad)
                            .addComponent(jSpn_edit_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_Edit_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_Cancelar1)
                            .addComponent(jBtn_Guardar1)))
                    .addComponent(jLbl_edit_Icon))
                .addGap(93, 93, 93))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Un Consultorio"));

        jLbl_buscar_Consultorio.setText("Consultorio");

        jcbx_Editar_Consultorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbx_Editar_ConsultorioItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_buscar_Consultorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbx_Editar_Consultorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_buscar_Consultorio)
                    .addComponent(jcbx_Editar_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnl_EditarLayout = new javax.swing.GroupLayout(jPnl_Editar);
        jPnl_Editar.setLayout(jPnl_EditarLayout);
        jPnl_EditarLayout.setHorizontalGroup(
            jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Edit_Consultorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPnl_EditarLayout.setVerticalGroup(
            jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_EditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Edit_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jPnl_Editar);

        jPnlBusq_Basica.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda  Basica"));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Campo");

        jcb_Buscar_Campo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero", "Piso", "Disponibilidad" }));

        javax.swing.GroupLayout jPnlBusq_BasicaLayout = new javax.swing.GroupLayout(jPnlBusq_Basica);
        jPnlBusq_Basica.setLayout(jPnlBusq_BasicaLayout);
        jPnlBusq_BasicaLayout.setHorizontalGroup(
            jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusq_BasicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_Buscar_Campo, 0, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Busqueda_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPnlBusq_BasicaLayout.setVerticalGroup(
            jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusq_BasicaLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Busqueda_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel9)
                    .addComponent(jcb_Buscar_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jTbl_Buscar.setAutoCreateRowSorter(true);
        jTbl_Buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Piso", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTbl_Buscar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTbl_Buscar.setDragEnabled(true);
        jScrollPane1.setViewportView(jTbl_Buscar);
        jTbl_Buscar.getColumnModel().getColumn(0).setMinWidth(60);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnl_BuscarLayout = new javax.swing.GroupLayout(jPnl_Buscar);
        jPnl_Buscar.setLayout(jPnl_BuscarLayout);
        jPnl_BuscarLayout.setHorizontalGroup(
            jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnlBusq_Basica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPnl_BuscarLayout.setVerticalGroup(
            jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlBusq_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPnl_Buscar);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Consultorios"));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Piso", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setDragEnabled(true);
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 217, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout jPnl_ListarLayout = new javax.swing.GroupLayout(jPnl_Listar);
        jPnl_Listar.setLayout(jPnl_ListarLayout);
        jPnl_ListarLayout.setHorizontalGroup(
            jPnl_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPnl_ListarLayout.setVerticalGroup(
            jPnl_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPnl_Listar);

        jPnEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Consultorios"));

        jLabel10.setText("Seleccione un consultorio que desee eliminar:");

        jCbx_Eliminar_Consultorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbx_Eliminar_ConsultorioItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPnEliminarLayout = new javax.swing.GroupLayout(jPnEliminar);
        jPnEliminar.setLayout(jPnEliminarLayout);
        jPnEliminarLayout.setHorizontalGroup(
            jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(jCbx_Eliminar_Consultorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnEliminarLayout.setVerticalGroup(
            jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEliminarLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbx_Eliminar_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Deleted_Consultorio.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));

        jLabel11.setText("Numero:");

        jTxtf_Numero_Eliminar.setEnabled(false);

        jLabel13.setText("Piso:");

        jTxtf_Piso_Eliminar.setEnabled(false);

        jLabel15.setText("Disponibilidad:");

        jTxtf_Disponibilidad_Eliminar.setEnabled(false);

        jBtn_Eliminar.setText("Eliminar");
        jBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EliminarActionPerformed(evt);
            }
        });

        jBtn_Cancelar_Eliminar.setText("Cancelar");
        jBtn_Cancelar_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Cancelar_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Deleted_ConsultorioLayout = new javax.swing.GroupLayout(jPanel_Deleted_Consultorio);
        jPanel_Deleted_Consultorio.setLayout(jPanel_Deleted_ConsultorioLayout);
        jPanel_Deleted_ConsultorioLayout.setHorizontalGroup(
            jPanel_Deleted_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Deleted_ConsultorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Deleted_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(jPanel_Deleted_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel_Deleted_ConsultorioLayout.createSequentialGroup()
                            .addComponent(jBtn_Cancelar_Eliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                            .addComponent(jBtn_Eliminar))
                        .addComponent(jTxtf_Disponibilidad_Eliminar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtf_Piso_Eliminar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtf_Numero_Eliminar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Deleted_ConsultorioLayout.setVerticalGroup(
            jPanel_Deleted_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Deleted_ConsultorioLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtf_Numero_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtf_Piso_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtf_Disponibilidad_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Deleted_ConsultorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_Eliminar)
                    .addComponent(jBtn_Cancelar_Eliminar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnl_EliminarLayout = new javax.swing.GroupLayout(jPnl_Eliminar);
        jPnl_Eliminar.setLayout(jPnl_EliminarLayout);
        jPnl_EliminarLayout.setHorizontalGroup(
            jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Deleted_Consultorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPnl_EliminarLayout.setVerticalGroup(
            jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Deleted_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPnl_Eliminar);

        jMenu1.setText("Archivo");

        jMPrincipal.setText("Menu Principal");
        jMenu1.add(jMPrincipal);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMSalir);

        jmenu_principal.add(jMenu1);

        setJMenuBar(jmenu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Guardar1ActionPerformed
        // TODO add your handling code here:
        
        try {
            if(validarDatosEditar()){               
                int Numero = Integer.parseInt(jftxtf_edit_Numero.getText());
                int Piso = Integer.parseInt(jSpn_edit_Piso.getValue().toString());
                String Disponibilidad = jSpn_edit_Estado.getValue().toString();
                
                Consultorio cons = new Consultorio();
                cons.Editar(this.idTempo, Numero, Piso, Disponibilidad);
                cargarListaConsultorios(jcbx_Editar_Consultorio);
            }
        }catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, "Error al ingresar datos "+ne, "Datos No Validos", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error General Editar"+e, "Datos No Validos ", JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_jBtn_Guardar1ActionPerformed

    private void jBtn_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Cancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_Cancelar1ActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        cargarListaConsultorios(jcbx_Editar_Consultorio);
        cargarListaConsultorios(jCbx_Eliminar_Consultorio);
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jPnl_EditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPnl_EditarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnl_EditarFocusGained

    private void jcbx_Editar_ConsultorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbx_Editar_ConsultorioItemStateChanged
        // TODO add your handling code here:
        try {
            Consultorio Consulto = (Consultorio) jcbx_Editar_Consultorio.getSelectedItem();
            jftxtf_edit_Numero.setText(String.valueOf(Consulto.getN_Consultorio()));
            jSpn_edit_Piso.setValue(Consulto.getPiso());
            jSpn_edit_Estado.setValue(Consulto.getDisponibilidad());
            this.idTempo = Consulto.getId();
            jPanel_Edit_Consultorio.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jcbx_Editar_ConsultorioItemStateChanged

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Campo = jcb_Buscar_Campo.getSelectedItem().toString();
        String Termino = jTxt_Busqueda_Basica.getText();
        Consultorio cons = new Consultorio();
        ArrayList<Consultorio> arrConsultorio = new ArrayList<Consultorio>();
        arrConsultorio = cons.Buscar(this.formarWhere(Campo, Termino));
        listConsultoriosTabla(arrConsultorio, jTbl_Buscar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        // TODO add your handling code here:
        limpiarCamposfrmNew();
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_GuardarActionPerformed
        // TODO add your handling code here:
        try {
            if(validarDatos()){
                int Numero = Integer.parseInt(jftxtf_Numero.getText());
                int Piso = Integer.parseInt(jSpn_Piso.getValue().toString());
                String Disponibilidad = jSpn_Estado.getValue().toString();
                                
                Consultorio cons = new Consultorio();
                if(cons.Nuevo(Numero, Piso, Disponibilidad)){
                    JOptionPane.showMessageDialog(rootPane, "Consultorio creado con exito", "Consultorio Creado", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, "Error al ingresar datos "+ne, "Datos No Validos", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error General "+e, "Datos No Validos ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_GuardarActionPerformed

    private void jBtn_Cancelar_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Cancelar_EliminarActionPerformed
        // TODO add your handling code here:
        limpiarCamposfrmEdit();
        this.idTempoEliminar = 0;
    }//GEN-LAST:event_jBtn_Cancelar_EliminarActionPerformed

    private void jBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EliminarActionPerformed
        // TODO add your handling code here:
        if (this.idTempoEliminar != 0){
            int confirmado = JOptionPane.showConfirmDialog(this, "¿Deseas Realmente Eliminar el Consultorio?","Eliminar Consultorio",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (JOptionPane.YES_OPTION == confirmado){
                Consultorio consTemp = new Consultorio();
                if(consTemp.Eliminar(idTempoEliminar)){
                    JOptionPane.showMessageDialog(rootPane, "El Consultorio se ha eliminado correctamente de la base de datos", "Consultorio Eliminado", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCamposfrmEdit();
                    cargarListaConsultorios(jCbx_Eliminar_Consultorio);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "NO se ha podido eliminar el consultorio", "Error Eliminando", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Operacion Cancelada", "Eliminar Consultorio", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtn_EliminarActionPerformed

    private void jCbx_Eliminar_ConsultorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbx_Eliminar_ConsultorioItemStateChanged
        // TODO add your handling code here:
        try {
            Consultorio consultorio = (Consultorio) jCbx_Eliminar_Consultorio.getSelectedItem();
            jTxtf_Numero_Eliminar.setText(String.valueOf(consultorio.getN_Consultorio()));
            jTxtf_Piso_Eliminar.setText(String.valueOf(consultorio.getPiso()));
            jTxtf_Disponibilidad_Eliminar.setText(consultorio.getDisponibilidad());
            this.idTempoEliminar = consultorio.getId();
            jPanel_Deleted_Consultorio.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jCbx_Eliminar_ConsultorioItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ListarConsultorios();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public String formarWhere (String Campo, String Valor){
        String Where = "1";       
        if (Campo.equalsIgnoreCase("Numero")){
            Where = "NUMERODECONSULTORIO = "+Valor+"";
        }else if (Campo.equalsIgnoreCase("Piso")){
            Where = "PISO = "+Valor+"";
        }else if (Campo.equalsIgnoreCase("Disponibilidad")){
            Where = "DISPONIBILIDAD LIKE '%"+Valor+"%'";
        }
        return Where;
    }
    
    public void listConsultoriosTabla (ArrayList<Consultorio> arrConsultorios, JTable tabla){
        
        DefaultTableModel modelBase = (DefaultTableModel) tabla.getModel();
        modelBase = limpiarTabla(modelBase);
        for (Consultorio consu : arrConsultorios) {
            Vector tempConsultorio = new Vector();
            tempConsultorio.add(consu.getN_Consultorio());
            tempConsultorio.add(consu.getPiso());
            tempConsultorio.add(consu.getDisponibilidad());
            modelBase.addRow(tempConsultorio);
        }
        tabla.setModel(modelBase);

    }
    
    public DefaultTableModel limpiarTabla (DefaultTableModel model){
        int filas = model.getRowCount();
        for (int i = 0;i<filas; i++) {
            model.removeRow(0); //Eliminacion en pila.
        }
        return model;
    }
    
    
    private boolean validarDatos (){
       
        if(jftxtf_Numero.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Se deben de ingresar todos los campos", "Datos No Validos", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }

    private boolean validarDatosEditar (){
       
        if(jftxtf_edit_Numero.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Se deben de ingresar todos los campos", "Datos No Validos", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
    
    public void limpiarCamposfrmNew(){
        jftxtf_Numero.setText("");
        jSpn_Piso.setValue(0);
        jSpn_Estado.setValue(0);
    }
    
    public void limpiarCamposfrmEdit(){
        jTxtf_Numero_Eliminar.setText("");
        jTxtf_Piso_Eliminar.setText("");
        jTxtf_Disponibilidad_Eliminar.setText("");
    }
    
    public static void cargarListaConsultorios(JComboBox combo){
        combo.removeAllItems();
        ArrayList <Consultorio> listConsultorios;
        Consultorio consu = new Consultorio();
        listConsultorios = consu.Buscar("1");
        for (Consultorio con : listConsultorios) {
            combo.addItem(con);
        }
    }

    public static void cargarListaConsultorios(JComboBox combo, int Id){
        combo.removeAllItems();
        ArrayList <Consultorio> listConsultorios;
        Consultorio consu = new Consultorio();
        listConsultorios = consu.Buscar("1");
        for (Consultorio con : listConsultorios) {
            combo.addItem(con);
            if (con.getId() == Id){
                combo.setSelectedItem(con);
            }
        }
    }
    
    public void ListarConsultorios(){
        ArrayList <Consultorio> listConsultorio;
        Consultorio consu = new Consultorio();
        listConsultorio = consu.Buscar("1");
        listConsultoriosTabla(listConsultorio,jTable1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsultorios().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Cancelar1;
    private javax.swing.JButton jBtn_Cancelar_Eliminar;
    private javax.swing.JButton jBtn_Eliminar;
    private javax.swing.JButton jBtn_Guardar;
    private javax.swing.JButton jBtn_Guardar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbx_Eliminar_Consultorio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbl_Descripcion;
    private javax.swing.JLabel jLbl_Disponibilidad;
    private javax.swing.JLabel jLbl_Numero;
    private javax.swing.JLabel jLbl_Piso;
    private javax.swing.JLabel jLbl_buscar_Consultorio;
    private javax.swing.JLabel jLbl_edit_Disponibilidad;
    private javax.swing.JLabel jLbl_edit_Icon;
    private javax.swing.JLabel jLbl_edit_Numero;
    private javax.swing.JLabel jLbl_edit_Piso;
    private javax.swing.JMenuItem jMPrincipal;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Deleted_Consultorio;
    private javax.swing.JPanel jPanel_Edit_Consultorio;
    private javax.swing.JPanel jPnEliminar;
    private javax.swing.JPanel jPnlBusq_Basica;
    private javax.swing.JPanel jPnl_Buscar;
    private javax.swing.JPanel jPnl_Editar;
    private javax.swing.JPanel jPnl_Eliminar;
    private javax.swing.JPanel jPnl_Listar;
    private javax.swing.JPanel jPnl_Nuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpn_Estado;
    private javax.swing.JSpinner jSpn_Piso;
    private javax.swing.JSpinner jSpn_edit_Estado;
    private javax.swing.JSpinner jSpn_edit_Piso;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTbl_Buscar;
    private javax.swing.JTextField jTxt_Busqueda_Basica;
    private javax.swing.JTextField jTxtf_Disponibilidad_Eliminar;
    private javax.swing.JTextField jTxtf_Numero_Eliminar;
    private javax.swing.JTextField jTxtf_Piso_Eliminar;
    private javax.swing.JComboBox jcb_Buscar_Campo;
    private javax.swing.JComboBox jcbx_Editar_Consultorio;
    private javax.swing.JFormattedTextField jftxtf_Numero;
    private javax.swing.JFormattedTextField jftxtf_edit_Numero;
    private javax.swing.JMenuBar jmenu_principal;
    // End of variables declaration//GEN-END:variables
}
