/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import Clases.*;import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kisuke
 */
public class frmCitas extends javax.swing.JFrame {

    
    int idTempoEditar, idTempoEliminar;
    
    /**
     * Creates new form frmOdontologos
     */
    public frmCitas() {
        initComponents();
        jPanel_Edit_Cita.setVisible(false);
        ListarCitas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPnl_Nuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLbl_Descripcion = new javax.swing.JLabel();
        jLbl_Fecha = new javax.swing.JLabel();
        jLbl_H_inicio = new javax.swing.JLabel();
        jftxf_H_Inicio = new javax.swing.JFormattedTextField();
        jLbl_H_Fin = new javax.swing.JLabel();
        jftxtf_H_Fin = new javax.swing.JFormattedTextField();
        jLbl_Numero_Documento = new javax.swing.JLabel();
        jLbl_Odontologo = new javax.swing.JLabel();
        jLbl_Consultorio = new javax.swing.JLabel();
        jBtn_Guardar = new javax.swing.JButton();
        jLbl_Icon = new javax.swing.JLabel();
        jBtn_Cancelar = new javax.swing.JButton();
        jDateChooser_Fecha = new com.toedter.calendar.JDateChooser();
        jCBx_Paciente = new javax.swing.JComboBox();
        jCBx_Odontologo = new javax.swing.JComboBox();
        jCBx_Consultorio = new javax.swing.JComboBox();
        jLbl_Tratamiento = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtA_Tramiento = new javax.swing.JTextArea();
        jPnl_Editar = new javax.swing.JPanel();
        jPanel_Edit_Cita = new javax.swing.JPanel();
        jBtn_Guardar1 = new javax.swing.JButton();
        jLbl_Edit_Icon = new javax.swing.JLabel();
        jBtn_Cancelar1 = new javax.swing.JButton();
        jLbl_Edit_Fecha = new javax.swing.JLabel();
        jDateChooser_Edit_Fecha = new com.toedter.calendar.JDateChooser();
        jLbl_Edit_H_inicio = new javax.swing.JLabel();
        jftxf_Edit_H_Inicio = new javax.swing.JFormattedTextField();
        jLbl_Edit_H_Fin = new javax.swing.JLabel();
        jftxtf_Edit_H_Fin = new javax.swing.JFormattedTextField();
        jLbl_Edit_Paciente = new javax.swing.JLabel();
        jCBx_Edit_Paciente = new javax.swing.JComboBox();
        jLbl_Edit_Odontologo = new javax.swing.JLabel();
        jCBx_Edit_Odontologo = new javax.swing.JComboBox();
        jLbl_Edit_Consultorio = new javax.swing.JLabel();
        jCBx_Edit_Consultorio = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtA_Edit_Tratamiento = new javax.swing.JTextArea();
        jLbl_Edit_Tratamiento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLbl_Edit_Cita = new javax.swing.JLabel();
        jCBx_Edit_Citas = new javax.swing.JComboBox();
        jPnl_Buscar = new javax.swing.JPanel();
        jPnlBusq_Basica = new javax.swing.JPanel();
        jTxt_Busqueda_Basica = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jcb_Buscar_Campo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Buscar = new javax.swing.JTable();
        jPnl_Eliminar = new javax.swing.JPanel();
        jPnEliminar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCbx_Eliminar_Cita = new javax.swing.JComboBox();
        jPanel_Deleted_Citas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTxtf_Fecha_Eliminar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtf_H_Inicio_Eliminar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtf_H_Fin_Eliminar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtf_Paciente_Eliminar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtf_Odontologo_Eliminar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtf_Consultorio_Eliminar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTxtf_Tratamiento_Eliminar = new javax.swing.JTextField();
        jBtn_Eliminar = new javax.swing.JButton();
        jBtn_Cancelar_Eliminar = new javax.swing.JButton();
        jPnl_Listar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jmenu_principal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMPrincipal = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Citas");

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Cita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLbl_Descripcion.setText("Por favor ingrese los datos de la cita.");

        jLbl_Fecha.setText("Fecha:");

        jLbl_H_inicio.setText("Hora Inicio:");

        jftxf_H_Inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));
        jftxf_H_Inicio.setToolTipText("HH:MM:SS");
        jftxf_H_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxf_H_InicioActionPerformed(evt);
            }
        });

        jLbl_H_Fin.setText("Hora Fin:");

        jftxtf_H_Fin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));
        jftxtf_H_Fin.setToolTipText("HH:MM:SS");

        jLbl_Numero_Documento.setText("Paciente:");

        jLbl_Odontologo.setText("Odontologo:");

        jLbl_Consultorio.setText("Consultorio:");

        jBtn_Guardar.setText("Guardar");
        jBtn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_GuardarActionPerformed(evt);
            }
        });

        jLbl_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/nuevousuario.png"))); // NOI18N

        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jDateChooser_Fecha.setDateFormatString("yyyy-MM-dd");

        jLbl_Tratamiento.setText("Tratamiento:");

        jTxtA_Tramiento.setColumns(20);
        jTxtA_Tramiento.setRows(5);
        jScrollPane3.setViewportView(jTxtA_Tramiento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLbl_Tratamiento)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLbl_Consultorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbl_H_Fin)
                                    .addComponent(jLbl_H_inicio)
                                    .addComponent(jLbl_Fecha)
                                    .addComponent(jLbl_Numero_Documento)
                                    .addComponent(jLbl_Odontologo))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jftxtf_H_Fin)
                                    .addComponent(jftxf_H_Inicio)
                                    .addComponent(jDateChooser_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBx_Paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBx_Odontologo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBx_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLbl_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtn_Cancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Guardar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLbl_Descripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_Fecha)
                    .addComponent(jDateChooser_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftxf_H_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_H_inicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftxtf_H_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_H_Fin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Numero_Documento)
                            .addComponent(jCBx_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Odontologo)
                            .addComponent(jCBx_Odontologo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Consultorio)
                            .addComponent(jCBx_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLbl_Icon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbl_Tratamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn_Guardar)
                    .addComponent(jBtn_Cancelar))
                .addGap(464, 464, 464))
        );

        javax.swing.GroupLayout jPnl_NuevoLayout = new javax.swing.GroupLayout(jPnl_Nuevo);
        jPnl_Nuevo.setLayout(jPnl_NuevoLayout);
        jPnl_NuevoLayout.setHorizontalGroup(
            jPnl_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPnl_NuevoLayout.setVerticalGroup(
            jPnl_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nuevo", jPnl_Nuevo);

        jPnl_Editar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPnl_EditarFocusGained(evt);
            }
        });

        jPanel_Edit_Cita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Citas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jBtn_Guardar1.setText("Guardar");
        jBtn_Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Guardar1ActionPerformed(evt);
            }
        });

        jLbl_Edit_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/Edit-Male-User-icon.png"))); // NOI18N

        jBtn_Cancelar1.setText("Cancelar");
        jBtn_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Cancelar1ActionPerformed(evt);
            }
        });

        jLbl_Edit_Fecha.setText("Fecha:");

        jDateChooser_Edit_Fecha.setDateFormatString("yyyy-MM-dd");

        jLbl_Edit_H_inicio.setText("Hora Inicio:");

        jftxf_Edit_H_Inicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));
        jftxf_Edit_H_Inicio.setToolTipText("HH:MM:SS");
        jftxf_Edit_H_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxf_Edit_H_InicioActionPerformed(evt);
            }
        });

        jLbl_Edit_H_Fin.setText("Hora Fin:");

        jftxtf_Edit_H_Fin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm:ss"))));
        jftxtf_Edit_H_Fin.setToolTipText("HH:MM:SS");

        jLbl_Edit_Paciente.setText("Paciente:");

        jLbl_Edit_Odontologo.setText("Odontologo:");

        jLbl_Edit_Consultorio.setText("Consultorio:");

        jTxtA_Edit_Tratamiento.setColumns(20);
        jTxtA_Edit_Tratamiento.setRows(5);
        jScrollPane4.setViewportView(jTxtA_Edit_Tratamiento);

        jLbl_Edit_Tratamiento.setText("Tratamiento:");

        javax.swing.GroupLayout jPanel_Edit_CitaLayout = new javax.swing.GroupLayout(jPanel_Edit_Cita);
        jPanel_Edit_Cita.setLayout(jPanel_Edit_CitaLayout);
        jPanel_Edit_CitaLayout.setHorizontalGroup(
            jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addContainerGap(138, Short.MAX_VALUE))
                    .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                        .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                                .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLbl_Edit_Consultorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbl_Edit_H_Fin)
                                    .addComponent(jLbl_Edit_H_inicio)
                                    .addComponent(jLbl_Edit_Fecha)
                                    .addComponent(jLbl_Edit_Paciente)
                                    .addComponent(jLbl_Edit_Odontologo))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jftxtf_Edit_H_Fin)
                                    .addComponent(jftxf_Edit_H_Inicio)
                                    .addComponent(jDateChooser_Edit_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBx_Edit_Paciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBx_Edit_Odontologo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBx_Edit_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLbl_Edit_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLbl_Edit_Tratamiento)
                            .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                                .addComponent(jBtn_Cancelar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn_Guardar1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_Edit_CitaLayout.setVerticalGroup(
            jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                        .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl_Edit_Fecha)
                            .addComponent(jDateChooser_Edit_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftxf_Edit_H_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_Edit_H_inicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftxtf_Edit_H_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_Edit_H_Fin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Edit_Paciente)
                            .addComponent(jCBx_Edit_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Edit_Odontologo)
                            .addComponent(jCBx_Edit_Odontologo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Edit_Consultorio)
                            .addComponent(jCBx_Edit_Consultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_Edit_CitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbl_Edit_Icon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbl_Edit_Tratamiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_CitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Cancelar1)
                    .addComponent(jBtn_Guardar1))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Una Cita"));

        jLbl_Edit_Cita.setText("Cita");

        jCBx_Edit_Citas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBx_Edit_CitasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_Edit_Cita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBx_Edit_Citas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Edit_Cita)
                    .addComponent(jCBx_Edit_Citas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnl_EditarLayout = new javax.swing.GroupLayout(jPnl_Editar);
        jPnl_Editar.setLayout(jPnl_EditarLayout);
        jPnl_EditarLayout.setHorizontalGroup(
            jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Edit_Cita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPnl_EditarLayout.setVerticalGroup(
            jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_EditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Edit_Cita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar", jPnl_Editar);

        jPnlBusq_Basica.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda  Basica"));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Campo");

        jcb_Buscar_Campo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fecha", "Hora Inicio", "Hora Fin", "Tratamiento", "Paciente", "Odontologo", "Consultorio" }));

        javax.swing.GroupLayout jPnlBusq_BasicaLayout = new javax.swing.GroupLayout(jPnlBusq_Basica);
        jPnlBusq_Basica.setLayout(jPnlBusq_BasicaLayout);
        jPnlBusq_BasicaLayout.setHorizontalGroup(
            jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusq_BasicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_Buscar_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Busqueda_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPnlBusq_BasicaLayout.setVerticalGroup(
            jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusq_BasicaLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Busqueda_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel9)
                    .addComponent(jcb_Buscar_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jTbl_Buscar.setAutoCreateRowSorter(true);
        jTbl_Buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora Inicio", "Hora Fin ", "Tratamiento", "Paciente", "Odontologo", "Consultorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTbl_Buscar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTbl_Buscar.setDragEnabled(true);
        jScrollPane1.setViewportView(jTbl_Buscar);
        jTbl_Buscar.getColumnModel().getColumn(0).setMinWidth(60);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnl_BuscarLayout = new javax.swing.GroupLayout(jPnl_Buscar);
        jPnl_Buscar.setLayout(jPnl_BuscarLayout);
        jPnl_BuscarLayout.setHorizontalGroup(
            jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnlBusq_Basica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnl_BuscarLayout.setVerticalGroup(
            jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlBusq_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPnl_Buscar);

        jPnEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Cita"));

        jLabel10.setText("Seleccione una cita que desee eliminar de la lista desplegable:");

        jCbx_Eliminar_Cita.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbx_Eliminar_CitaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPnEliminarLayout = new javax.swing.GroupLayout(jPnEliminar);
        jPnEliminar.setLayout(jPnEliminarLayout);
        jPnEliminarLayout.setHorizontalGroup(
            jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addComponent(jCbx_Eliminar_Cita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnEliminarLayout.setVerticalGroup(
            jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEliminarLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbx_Eliminar_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Deleted_Citas.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Cita"));

        jLabel11.setText("Fecha:");

        jTxtf_Fecha_Eliminar.setEnabled(false);

        jLabel12.setText("Hora Inicio:");

        jTxtf_H_Inicio_Eliminar.setEnabled(false);

        jLabel13.setText("Hora Fin:");

        jTxtf_H_Fin_Eliminar.setEnabled(false);

        jLabel14.setText("Paciente:");

        jTxtf_Paciente_Eliminar.setEnabled(false);

        jLabel15.setText("Odontologo:");

        jTxtf_Odontologo_Eliminar.setEnabled(false);

        jLabel16.setText("Consultorio:");

        jTxtf_Consultorio_Eliminar.setEnabled(false);

        jLabel18.setText("Tratamiento:");

        jTxtf_Tratamiento_Eliminar.setEnabled(false);

        jBtn_Eliminar.setText("Eliminar");
        jBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EliminarActionPerformed(evt);
            }
        });

        jBtn_Cancelar_Eliminar.setText("Cancelar");
        jBtn_Cancelar_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Cancelar_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Deleted_CitasLayout = new javax.swing.GroupLayout(jPanel_Deleted_Citas);
        jPanel_Deleted_Citas.setLayout(jPanel_Deleted_CitasLayout);
        jPanel_Deleted_CitasLayout.setHorizontalGroup(
            jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Deleted_CitasLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jBtn_Cancelar_Eliminar)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Eliminar)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Deleted_CitasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtf_Tratamiento_Eliminar)
                    .addGroup(jPanel_Deleted_CitasLayout.createSequentialGroup()
                        .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtf_Odontologo_Eliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(jTxtf_H_Fin_Eliminar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtf_Fecha_Eliminar, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jTxtf_H_Inicio_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jTxtf_Paciente_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jTxtf_Consultorio_Eliminar))))
                .addGap(54, 54, 54))
        );
        jPanel_Deleted_CitasLayout.setVerticalGroup(
            jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Deleted_CitasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtf_Fecha_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtf_H_Inicio_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtf_H_Fin_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtf_Paciente_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtf_Odontologo_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtf_Consultorio_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtf_Tratamiento_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Deleted_CitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Eliminar)
                    .addComponent(jBtn_Cancelar_Eliminar))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPnl_EliminarLayout = new javax.swing.GroupLayout(jPnl_Eliminar);
        jPnl_Eliminar.setLayout(jPnl_EliminarLayout);
        jPnl_EliminarLayout.setHorizontalGroup(
            jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_Deleted_Citas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPnl_EliminarLayout.setVerticalGroup(
            jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Deleted_Citas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPnl_Eliminar);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Citas"));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora Incio", "Hora Fin", "Tratamiento", "Paciente", "Odontologo", "Consultorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setDragEnabled(true);
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout jPnl_ListarLayout = new javax.swing.GroupLayout(jPnl_Listar);
        jPnl_Listar.setLayout(jPnl_ListarLayout);
        jPnl_ListarLayout.setHorizontalGroup(
            jPnl_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_ListarLayout.setVerticalGroup(
            jPnl_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPnl_Listar);

        jMenu1.setText("Archivo");

        jMPrincipal.setText("Menu Principal");
        jMenu1.add(jMPrincipal);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMSalir);

        jmenu_principal.add(jMenu1);

        setJMenuBar(jmenu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Guardar1ActionPerformed
        // TODO add your handling code here:
        
        try {
            if(validarDatosEditar()){
                Date Fecha = jDateChooser_Edit_Fecha.getDate();
                String H_Inicio = jftxf_Edit_H_Inicio.getText();
                String H_Fin = jftxtf_Edit_H_Fin.getText();
                Paciente paciente = (Paciente) jCBx_Edit_Paciente.getSelectedItem();
                Odontologos odontologo = (Odontologos) jCBx_Edit_Odontologo.getSelectedItem();
                Consultorio consultorio = (Consultorio) jCBx_Edit_Consultorio.getSelectedItem();
                String Tratamiento = jTxtA_Edit_Tratamiento.getText();
                 
                Citas cit = new Citas();
                cit.Editar(this.idTempoEditar, Fecha, H_Inicio, H_Fin, Tratamiento, paciente, odontologo, consultorio);
                cargarListaCitas(jCBx_Edit_Citas);
            }
        }catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, "Error al ingresar datos "+ne, "Datos No Validos", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error General Editar"+e, "Datos No Validos ", JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_jBtn_Guardar1ActionPerformed

    private void jBtn_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Cancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_Cancelar1ActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        CargarListasObjetos();
        cargarListaCitas(jCBx_Edit_Citas);
        cargarListaCitas(jCbx_Eliminar_Cita);
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jPnl_EditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPnl_EditarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnl_EditarFocusGained

    private void jCBx_Edit_CitasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBx_Edit_CitasItemStateChanged
        // TODO add your handling code here:
        try {
            Citas citas = (Citas) jCBx_Edit_Citas.getSelectedItem();
            jDateChooser_Edit_Fecha.setDate(citas.getFecha());
            jftxf_Edit_H_Inicio.setText(citas.getHora_Inicio());
            jftxtf_Edit_H_Fin.setText(citas.getHora_Fin());
            
            int IdPaciente = citas.getPaciente().getId();
            int IdOdontologo = citas.getOdontologo().getId();
            int IdConsultorio = citas.getConsultorio().getId();
            
            CargarListasObjetos(IdPaciente, IdOdontologo, IdConsultorio);
            jTxtA_Edit_Tratamiento.setText(citas.getTratamiento());
            this.idTempoEditar = citas.getId();
            jPanel_Edit_Cita.setVisible(true);
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jCBx_Edit_CitasItemStateChanged

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Campo = jcb_Buscar_Campo.getSelectedItem().toString();
        String Termino = jTxt_Busqueda_Basica.getText();
        Citas ct = new Citas();
        ArrayList<Citas> arrCitas = new ArrayList<Citas>();
        String where = this.formarWhere(Campo, Termino);
        if (Campo.equalsIgnoreCase("Paciente")){
            arrCitas = ct.BuscarVistaCita(where,"citasvspaciente");
        }else if (Campo.equalsIgnoreCase("Odontologo")){
            arrCitas = ct.BuscarVistaCita(where,"citasvsodontologo");
        }else if (Campo.equalsIgnoreCase("Consultorio")){
            arrCitas = ct.BuscarVistaCita(where,"citasvsconsultorio");
        }else{
            arrCitas = ct.Buscar(where);
        }
        listCitasTabla(arrCitas, jTbl_Buscar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        // TODO add your handling code here:
        limpiarCamposfrmNew();
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_GuardarActionPerformed
        // TODO add your handling code here:
        try {
            if(validarDatos()){
                Date Fecha = jDateChooser_Fecha.getDate();
                String Hora_Inicio = jftxf_H_Inicio.getText();
                String Hora_Fin = jftxtf_H_Fin.getText();
                String Tratamiento = jTxtA_Tramiento.getText();
                Paciente paciente = (Paciente) jCBx_Paciente.getSelectedItem();
                Odontologos odontologo = (Odontologos) jCBx_Odontologo.getSelectedItem();
                Consultorio consultorio = (Consultorio) jCBx_Consultorio.getSelectedItem();
                
                Citas cita = new Citas();
                if(cita.Nuevo(Fecha, Hora_Inicio, Hora_Fin, Tratamiento, paciente, odontologo, consultorio)){
                    JOptionPane.showMessageDialog(rootPane, "Cita Creada Con Exito", "Creacion de Citas", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCamposfrmNew();
                }
            }
        }catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, "Error al ingresar datos "+ne, "Datos No Validos", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error General "+e, "Datos No Validos ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_GuardarActionPerformed

    private void jftxf_H_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxf_H_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxf_H_InicioActionPerformed

    private void jBtn_Cancelar_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Cancelar_EliminarActionPerformed
        // TODO add your handling code here:
        limpiarCamposfrmEdit();
        this.idTempoEliminar = 0;
    }//GEN-LAST:event_jBtn_Cancelar_EliminarActionPerformed

    private void jBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EliminarActionPerformed
        // TODO add your handling code here:
        if (this.idTempoEliminar != 0){
            int confirmado = JOptionPane.showConfirmDialog(this, "¿Deseas Realmente Eliminar la cita?","Eliminar Cita",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (JOptionPane.YES_OPTION == confirmado){
                Citas odTemp = new Citas();
                if(odTemp.Eliminar(idTempoEliminar)){
                    JOptionPane.showMessageDialog(rootPane, "La cita se ha eliminado correctamente de la base de datos", "Eliminar Cita", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCamposfrmEdit();
                    cargarListaCitas(jCbx_Eliminar_Cita);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "NO se ha podido eliminar la cita", "Error Eliminar Cita", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Operacion Cancelada", "Eliminar Cita", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtn_EliminarActionPerformed

    private void jCbx_Eliminar_CitaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbx_Eliminar_CitaItemStateChanged
        // TODO add your handling code here:
        try {
            Citas Cita = (Citas) jCbx_Eliminar_Cita.getSelectedItem();
            jTxtf_Fecha_Eliminar.setText(Utility.DateToString(Cita.getFecha(), "yyyy-MM-dd"));
            jTxtf_H_Inicio_Eliminar.setText(Cita.getHora_Inicio());
            jTxtf_H_Fin_Eliminar.setText(Cita.getHora_Fin());
            jTxtf_Tratamiento_Eliminar.setText(Cita.getTratamiento());
            jTxtf_Paciente_Eliminar.setText(Cita.getPaciente().getNombres()+" "+Cita.getPaciente().getApellidos());
            jTxtf_Odontologo_Eliminar.setText(Cita.getOdontologo().getNombres()+" "+Cita.getOdontologo().getApellidos());
            jTxtf_Consultorio_Eliminar.setText(String.valueOf(Cita.getConsultorio().getN_Consultorio()));
            jTxtf_Tratamiento_Eliminar.setText(Cita.getTratamiento());
            this.idTempoEliminar = Cita.getId();
            jPanel_Deleted_Citas.setVisible(true);
        } catch (Exception e) {
            
        }

    }//GEN-LAST:event_jCbx_Eliminar_CitaItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ListarCitas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jftxf_Edit_H_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxf_Edit_H_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxf_Edit_H_InicioActionPerformed
    
    public String formarWhere (String Campo, String Valor){
       String Where = "1";       
        if (Campo.equalsIgnoreCase("Fecha")){
            Where = "FECHA = '"+Valor+"'";
        }else if (Campo.equalsIgnoreCase("Hora Inicio")){
            Where = "HORADEINICIO = '"+Valor+"'";
        }else if (Campo.equalsIgnoreCase("Hora Fin")){
            Where = "HORAFIN = '"+Valor+"'";
        }else if (Campo.equalsIgnoreCase("Tratamiento")){
            Where = "TRATAMIENTO LIKE '%"+Valor+"%'";
        }else if (Campo.equalsIgnoreCase("Paciente")){
            Where = "NOMBRES LIKE '%"+Valor+"%'";
        }else if (Campo.equalsIgnoreCase("Odontologo")){
            Where = "NOMBRES LIKE '%"+Valor+"%'";
        }else if (Campo.equalsIgnoreCase("Consultorio")){
            Where = "NUMERODECONSULTORIO = "+Valor+"";
        }
        return Where;
    }   
    
    private boolean validarDatos (){       
        if(jftxf_H_Inicio.getText().isEmpty() || jftxtf_H_Fin.getText().isEmpty() || jTxtA_Tramiento.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Se deben de ingresar todos los campos", "Datos No Validos", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }

    private boolean validarDatosEditar (){
        if(jftxf_Edit_H_Inicio.getText().isEmpty() || jftxtf_Edit_H_Fin.getText().isEmpty() || jTxtA_Edit_Tratamiento.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Se deben de ingresar todos los campos", "Datos No Validos", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
    
    public void limpiarCamposfrmNew(){
        jDateChooser_Fecha.setDate(new Date(0,0,0));
        jftxf_H_Inicio.setText("00:00:00");
        jftxtf_H_Fin.setText("00:00:00");
        CargarListasObjetos();
        jTxtA_Tramiento.setText("");
    }
    
    public void limpiarCamposfrmEdit(){
        jDateChooser_Edit_Fecha.setDate(new Date(0,0,0));
        jftxf_Edit_H_Inicio.setText("00:00:00");
        jftxtf_Edit_H_Fin.setText("00:00:00");
        CargarListasObjetos();
        jTxtA_Edit_Tratamiento.setText("");
    }
    
    public void cargarListaCitas(JComboBox combo){
        combo.removeAllItems();
        ArrayList <Citas> listCitas;
        Citas cita = new Citas();
        listCitas = cita.Buscar("1");
        for (Citas cit : listCitas) {
            combo.addItem(cit);
        }
    }
    
    public DefaultTableModel limpiarTabla (DefaultTableModel model){
        int filas = model.getRowCount();
        for (int i = 0;i<filas; i++) {
            model.removeRow(0); //Eliminacion en pila.
        }
        return model;
    }
    
    public void listCitasTabla (ArrayList<Citas> arrCitas, JTable tabla){
        
        DefaultTableModel modelBase = (DefaultTableModel) tabla.getModel();
        modelBase = limpiarTabla(modelBase);
        for (Citas cit : arrCitas) {
            Vector tempCitas = new Vector();
            tempCitas.add(cit.getFecha());
            tempCitas.add(cit.getHora_Inicio());
            tempCitas.add(cit.getHora_Fin());
            tempCitas.add(cit.getTratamiento());
            tempCitas.add(cit.getPaciente().getNombres()+" "+cit.getPaciente().getApellidos());
            tempCitas.add(cit.getOdontologo().getNombres()+" "+cit.getOdontologo().getApellidos());
            tempCitas.add(cit.getConsultorio().getN_Consultorio()+" - Piso "+cit.getConsultorio().getPiso());
            modelBase.addRow(tempCitas);
        }
        tabla.setModel(modelBase);
    }
    
    public void ListarCitas(){
        ArrayList <Citas> listCitas;
        Citas cita = new Citas();
        listCitas = cita.Buscar("1");
        listCitasTabla(listCitas,jTable1);
    }
    
    public void CargarListasObjetos (){
        frmPacientes.cargarListaPacientes(jCBx_Paciente);
        frmOdontologos.cargarListaOdontologos(jCBx_Odontologo);
        frmConsultorios.cargarListaConsultorios(jCBx_Consultorio);
    }

    public void CargarListasObjetos (int idPaciente, int idOdontologo, int idConsultorio){
        frmPacientes.cargarListaPacientes(jCBx_Edit_Paciente, idPaciente);
        frmOdontologos.cargarListaOdontologos(jCBx_Edit_Odontologo, idOdontologo);
        frmConsultorios.cargarListaConsultorios(jCBx_Edit_Consultorio, idConsultorio);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCitas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Cancelar1;
    private javax.swing.JButton jBtn_Cancelar_Eliminar;
    private javax.swing.JButton jBtn_Eliminar;
    private javax.swing.JButton jBtn_Guardar;
    private javax.swing.JButton jBtn_Guardar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCBx_Consultorio;
    private javax.swing.JComboBox jCBx_Edit_Citas;
    private javax.swing.JComboBox jCBx_Edit_Consultorio;
    private javax.swing.JComboBox jCBx_Edit_Odontologo;
    private javax.swing.JComboBox jCBx_Edit_Paciente;
    private javax.swing.JComboBox jCBx_Odontologo;
    private javax.swing.JComboBox jCBx_Paciente;
    private javax.swing.JComboBox jCbx_Eliminar_Cita;
    private com.toedter.calendar.JDateChooser jDateChooser_Edit_Fecha;
    private com.toedter.calendar.JDateChooser jDateChooser_Fecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbl_Consultorio;
    private javax.swing.JLabel jLbl_Descripcion;
    private javax.swing.JLabel jLbl_Edit_Cita;
    private javax.swing.JLabel jLbl_Edit_Consultorio;
    private javax.swing.JLabel jLbl_Edit_Fecha;
    private javax.swing.JLabel jLbl_Edit_H_Fin;
    private javax.swing.JLabel jLbl_Edit_H_inicio;
    private javax.swing.JLabel jLbl_Edit_Icon;
    private javax.swing.JLabel jLbl_Edit_Odontologo;
    private javax.swing.JLabel jLbl_Edit_Paciente;
    private javax.swing.JLabel jLbl_Edit_Tratamiento;
    private javax.swing.JLabel jLbl_Fecha;
    private javax.swing.JLabel jLbl_H_Fin;
    private javax.swing.JLabel jLbl_H_inicio;
    private javax.swing.JLabel jLbl_Icon;
    private javax.swing.JLabel jLbl_Numero_Documento;
    private javax.swing.JLabel jLbl_Odontologo;
    private javax.swing.JLabel jLbl_Tratamiento;
    private javax.swing.JMenuItem jMPrincipal;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Deleted_Citas;
    private javax.swing.JPanel jPanel_Edit_Cita;
    private javax.swing.JPanel jPnEliminar;
    private javax.swing.JPanel jPnlBusq_Basica;
    private javax.swing.JPanel jPnl_Buscar;
    private javax.swing.JPanel jPnl_Editar;
    private javax.swing.JPanel jPnl_Eliminar;
    private javax.swing.JPanel jPnl_Listar;
    private javax.swing.JPanel jPnl_Nuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTbl_Buscar;
    private javax.swing.JTextArea jTxtA_Edit_Tratamiento;
    private javax.swing.JTextArea jTxtA_Tramiento;
    private javax.swing.JTextField jTxt_Busqueda_Basica;
    private javax.swing.JTextField jTxtf_Consultorio_Eliminar;
    private javax.swing.JTextField jTxtf_Fecha_Eliminar;
    private javax.swing.JTextField jTxtf_H_Fin_Eliminar;
    private javax.swing.JTextField jTxtf_H_Inicio_Eliminar;
    private javax.swing.JTextField jTxtf_Odontologo_Eliminar;
    private javax.swing.JTextField jTxtf_Paciente_Eliminar;
    private javax.swing.JTextField jTxtf_Tratamiento_Eliminar;
    private javax.swing.JComboBox jcb_Buscar_Campo;
    private javax.swing.JFormattedTextField jftxf_Edit_H_Inicio;
    private javax.swing.JFormattedTextField jftxf_H_Inicio;
    private javax.swing.JFormattedTextField jftxtf_Edit_H_Fin;
    private javax.swing.JFormattedTextField jftxtf_H_Fin;
    private javax.swing.JMenuBar jmenu_principal;
    // End of variables declaration//GEN-END:variables
}
