/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import Clases.*;import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
;

/**
 *
 * @author Kisuke
 */
public class frmOdontologos extends javax.swing.JFrame {

    
    int idTempo, idTempoEliminar;
    
    /**
     * Creates new form frmOdontologos
     */
    public frmOdontologos() {
        initComponents();
        jPanel_Edit_Odontologo.setVisible(false);
        ListarOdontologos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPnl_Nuevo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLbl_Nombres = new javax.swing.JLabel();
        jftxtf_Nombres = new javax.swing.JFormattedTextField(new String());
        jLbl_Apellidos = new javax.swing.JLabel();
        jftxf_Apellidos = new javax.swing.JFormattedTextField();
        jLbl_Telefono = new javax.swing.JLabel();
        jftxtf_Telefono = new javax.swing.JFormattedTextField();
        jLbl_Numero_Documento = new javax.swing.JLabel();
        jftxtf_N_Documento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jftxtf_Correo = new javax.swing.JFormattedTextField();
        jLbl_Experiencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbl_Salario = new javax.swing.JLabel();
        jftxtf_Salario = new javax.swing.JFormattedTextField();
        jLbl_Direccion = new javax.swing.JLabel();
        jftxtf_Direccion = new javax.swing.JFormattedTextField();
        jBtn_Guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtn_Cancelar = new javax.swing.JButton();
        jSpn_Experiencia = new javax.swing.JSpinner();
        jPnl_Editar = new javax.swing.JPanel();
        jPanel_Edit_Odontologo = new javax.swing.JPanel();
        jLbl_Nombres1 = new javax.swing.JLabel();
        jftxtf_Nombres1 = new javax.swing.JFormattedTextField(new String());
        jLbl_Apellidos1 = new javax.swing.JLabel();
        jftxf_Apellidos1 = new javax.swing.JFormattedTextField();
        jLbl_Telefono1 = new javax.swing.JLabel();
        jftxtf_Telefono1 = new javax.swing.JFormattedTextField();
        jLbl_Numero_Documento1 = new javax.swing.JLabel();
        jftxtf_N_Documento1 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jftxtf_Correo1 = new javax.swing.JFormattedTextField();
        jLbl_Experiencia1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLbl_Salario1 = new javax.swing.JLabel();
        jftxtf_Salario1 = new javax.swing.JFormattedTextField();
        jLbl_Direccion1 = new javax.swing.JLabel();
        jftxtf_Direccion1 = new javax.swing.JFormattedTextField();
        jBtn_Guardar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBtn_Cancelar1 = new javax.swing.JButton();
        jSpn_Edit_Experiencia = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPnl_Buscar = new javax.swing.JPanel();
        jPnlBusq_Basica = new javax.swing.JPanel();
        jTxt_Busqueda_Basica = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jcb_Buscar_Campo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbl_Buscar = new javax.swing.JTable();
        jPnl_Eliminar = new javax.swing.JPanel();
        jPnEliminar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jCbx_Eliminar_Odontologo = new javax.swing.JComboBox();
        jPanel_Deleted_Odontologo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTxtf_Nombres_Eliminar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtf_Apellidos_Eliminar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtf_Telefono_Eliminar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtf_Documento_Eliminar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtf_Correo_Eliminar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtf_Experiencia_Eliminar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTxtf_Salario_Eliminar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTxtf_Direccion_Eliminar = new javax.swing.JTextField();
        jBtn_Eliminar = new javax.swing.JButton();
        jBtn_Cancelar_Eliminar = new javax.swing.JButton();
        jPnl_Listar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jmenu_principal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMPrincipal = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Odontologos");

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Odontologo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLabel1.setText("Por favor ingrese los datos del odontologo.");

        jLbl_Nombres.setText("Nombres");

        jLbl_Apellidos.setText("Apellidos");

        jftxf_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxf_ApellidosActionPerformed(evt);
            }
        });

        jLbl_Telefono.setText("Telefono");

        jftxtf_Telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));

        jLbl_Numero_Documento.setText("Numero Documento:");

        jftxtf_N_Documento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#############"))));

        jLabel3.setText("Correo Electronico:");

        jLbl_Experiencia.setText("Tiempo Experiencia:");

        jLabel2.setText("Años");

        jLbl_Salario.setText("Salario:");

        jftxtf_Salario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("############"))));

        jLbl_Direccion.setText("Direccion:");

        jBtn_Guardar.setText("Guardar");
        jBtn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_GuardarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/nuevousuario.png"))); // NOI18N

        jBtn_Cancelar.setText("Cancelar");
        jBtn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CancelarActionPerformed(evt);
            }
        });

        jSpn_Experiencia.setModel(new javax.swing.SpinnerNumberModel(1, 0, 50, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtn_Cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn_Guardar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLbl_Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLbl_Numero_Documento))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jSpn_Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(44, 44, 44)
                                            .addComponent(jLabel2))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jftxtf_Correo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(jftxtf_N_Documento))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLbl_Telefono)
                                        .addComponent(jLbl_Apellidos)
                                        .addComponent(jLbl_Nombres))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jftxf_Apellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addComponent(jftxtf_Nombres, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jftxtf_Telefono)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLbl_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLbl_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jftxtf_Direccion)
                                        .addComponent(jftxtf_Salario)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftxtf_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_Nombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftxf_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_Apellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jftxtf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_Telefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Numero_Documento)
                            .addComponent(jftxtf_N_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jftxtf_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Experiencia)
                            .addComponent(jLabel2)
                            .addComponent(jSpn_Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Salario)
                            .addComponent(jftxtf_Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Direccion)
                    .addComponent(jftxtf_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Guardar)
                    .addComponent(jBtn_Cancelar))
                .addGap(204, 204, 204))
        );

        javax.swing.GroupLayout jPnl_NuevoLayout = new javax.swing.GroupLayout(jPnl_Nuevo);
        jPnl_Nuevo.setLayout(jPnl_NuevoLayout);
        jPnl_NuevoLayout.setHorizontalGroup(
            jPnl_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPnl_NuevoLayout.setVerticalGroup(
            jPnl_NuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_NuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nuevo", jPnl_Nuevo);

        jPnl_Editar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPnl_EditarFocusGained(evt);
            }
        });

        jPanel_Edit_Odontologo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Odontologos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLbl_Nombres1.setText("Nombres");

        jLbl_Apellidos1.setText("Apellidos");

        jftxf_Apellidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftxf_Apellidos1ActionPerformed(evt);
            }
        });

        jLbl_Telefono1.setText("Telefono");

        jftxtf_Telefono1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));

        jLbl_Numero_Documento1.setText("Numero Documento:");

        jftxtf_N_Documento1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#############"))));

        jLabel6.setText("Correo Electronico:");

        jLbl_Experiencia1.setText("Tiempo Experiencia:");

        jLabel7.setText("Años");

        jLbl_Salario1.setText("Salario:");

        jftxtf_Salario1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("############"))));

        jLbl_Direccion1.setText("Direccion:");

        jBtn_Guardar1.setText("Guardar");
        jBtn_Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Guardar1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/img/Edit-Male-User-icon.png"))); // NOI18N

        jBtn_Cancelar1.setText("Cancelar");
        jBtn_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Cancelar1ActionPerformed(evt);
            }
        });

        jSpn_Edit_Experiencia.setModel(new javax.swing.SpinnerNumberModel(1, 0, 50, 1));

        javax.swing.GroupLayout jPanel_Edit_OdontologoLayout = new javax.swing.GroupLayout(jPanel_Edit_Odontologo);
        jPanel_Edit_Odontologo.setLayout(jPanel_Edit_OdontologoLayout);
        jPanel_Edit_OdontologoLayout.setHorizontalGroup(
            jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                        .addComponent(jBtn_Cancelar1)
                        .addGap(21, 21, 21)
                        .addComponent(jBtn_Guardar1))
                    .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                            .addComponent(jLbl_Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jftxtf_Direccion1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Edit_OdontologoLayout.createSequentialGroup()
                            .addComponent(jLbl_Salario1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jftxtf_Salario1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                                .addComponent(jLbl_Experiencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpn_Edit_Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                                    .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLbl_Numero_Documento1)
                                        .addComponent(jLabel6))
                                    .addGap(22, 22, 22)
                                    .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jftxtf_N_Documento1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                        .addComponent(jftxtf_Correo1, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                                    .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLbl_Telefono1)
                                        .addComponent(jLbl_Apellidos1))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jftxf_Apellidos1)
                                        .addComponent(jftxtf_Telefono1)))
                                .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                                    .addComponent(jLbl_Nombres1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jftxtf_Nombres1))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Edit_OdontologoLayout.setVerticalGroup(
            jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Nombres1)
                    .addComponent(jftxtf_Nombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftxf_Apellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_Apellidos1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftxtf_Telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_Telefono1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Numero_Documento1)
                            .addComponent(jftxtf_N_Documento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jftxtf_Correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Experiencia1)
                            .addComponent(jLabel7)
                            .addComponent(jSpn_Edit_Experiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl_Salario1)
                            .addComponent(jftxtf_Salario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_Edit_OdontologoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Direccion1)
                    .addComponent(jftxtf_Direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Cancelar1)
                    .addComponent(jBtn_Guardar1)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione Un Odontologo"));

        jLabel5.setText("Odontologos:");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnl_EditarLayout = new javax.swing.GroupLayout(jPnl_Editar);
        jPnl_Editar.setLayout(jPnl_EditarLayout);
        jPnl_EditarLayout.setHorizontalGroup(
            jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Edit_Odontologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPnl_EditarLayout.setVerticalGroup(
            jPnl_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl_EditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Edit_Odontologo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jPnl_Editar);

        jPnlBusq_Basica.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda  Basica"));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Campo");

        jcb_Buscar_Campo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombres", "Apellidos", "Telefono", "Identificacion", "Correo", "Tiempo Experiencia", "Salario", "Direccion" }));

        javax.swing.GroupLayout jPnlBusq_BasicaLayout = new javax.swing.GroupLayout(jPnlBusq_Basica);
        jPnlBusq_Basica.setLayout(jPnlBusq_BasicaLayout);
        jPnlBusq_BasicaLayout.setHorizontalGroup(
            jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusq_BasicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcb_Buscar_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_Busqueda_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPnlBusq_BasicaLayout.setVerticalGroup(
            jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBusq_BasicaLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPnlBusq_BasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_Busqueda_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel9)
                    .addComponent(jcb_Buscar_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jTbl_Buscar.setAutoCreateRowSorter(true);
        jTbl_Buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Telefono", "Documento", "Correo", "Experiencia", "Salario", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTbl_Buscar.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTbl_Buscar.setDragEnabled(true);
        jScrollPane1.setViewportView(jTbl_Buscar);
        jTbl_Buscar.getColumnModel().getColumn(0).setMinWidth(60);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnl_BuscarLayout = new javax.swing.GroupLayout(jPnl_Buscar);
        jPnl_Buscar.setLayout(jPnl_BuscarLayout);
        jPnl_BuscarLayout.setHorizontalGroup(
            jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnlBusq_Basica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPnl_BuscarLayout.setVerticalGroup(
            jPnl_BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_BuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlBusq_Basica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPnl_Buscar);

        jPnEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Odontologo"));

        jLabel10.setText("Seleccione un odontologo que desee eliminar de la lista desplegable:");

        jCbx_Eliminar_Odontologo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbx_Eliminar_OdontologoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPnEliminarLayout = new javax.swing.GroupLayout(jPnEliminar);
        jPnEliminar.setLayout(jPnEliminarLayout);
        jPnEliminarLayout.setHorizontalGroup(
            jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addComponent(jCbx_Eliminar_Odontologo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPnEliminarLayout.setVerticalGroup(
            jPnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEliminarLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbx_Eliminar_Odontologo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Deleted_Odontologo.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Odontologo"));

        jLabel11.setText("Nombres");

        jTxtf_Nombres_Eliminar.setEnabled(false);

        jLabel12.setText("Apellidos:");

        jTxtf_Apellidos_Eliminar.setEnabled(false);

        jLabel13.setText("Telefono:");

        jTxtf_Telefono_Eliminar.setEnabled(false);

        jLabel14.setText("Documento:");

        jTxtf_Documento_Eliminar.setEnabled(false);

        jLabel15.setText("Correo:");

        jTxtf_Correo_Eliminar.setEnabled(false);

        jLabel16.setText("Experiencia:");

        jTxtf_Experiencia_Eliminar.setEnabled(false);

        jLabel17.setText("Años");

        jLabel18.setText("Salario:");

        jTxtf_Salario_Eliminar.setEnabled(false);

        jLabel19.setText("Direccion:");

        jTxtf_Direccion_Eliminar.setEnabled(false);

        jBtn_Eliminar.setText("Eliminar");
        jBtn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_EliminarActionPerformed(evt);
            }
        });

        jBtn_Cancelar_Eliminar.setText("Cancelar");
        jBtn_Cancelar_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Cancelar_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Deleted_OdontologoLayout = new javax.swing.GroupLayout(jPanel_Deleted_Odontologo);
        jPanel_Deleted_Odontologo.setLayout(jPanel_Deleted_OdontologoLayout);
        jPanel_Deleted_OdontologoLayout.setHorizontalGroup(
            jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Deleted_OdontologoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtf_Salario_Eliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addComponent(jTxtf_Correo_Eliminar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtf_Telefono_Eliminar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtf_Nombres_Eliminar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtf_Apellidos_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtf_Documento_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Deleted_OdontologoLayout.createSequentialGroup()
                        .addComponent(jTxtf_Experiencia_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addComponent(jTxtf_Direccion_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(jPanel_Deleted_OdontologoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jBtn_Cancelar_Eliminar)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Deleted_OdontologoLayout.setVerticalGroup(
            jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Deleted_OdontologoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtf_Nombres_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtf_Apellidos_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtf_Telefono_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtf_Documento_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtf_Correo_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtf_Experiencia_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtf_Salario_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtf_Direccion_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Deleted_OdontologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Eliminar)
                    .addComponent(jBtn_Cancelar_Eliminar))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPnl_EliminarLayout = new javax.swing.GroupLayout(jPnl_Eliminar);
        jPnl_Eliminar.setLayout(jPnl_EliminarLayout);
        jPnl_EliminarLayout.setHorizontalGroup(
            jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_Deleted_Odontologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPnl_EliminarLayout.setVerticalGroup(
            jPnl_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_EliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Deleted_Odontologo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPnl_Eliminar);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Listar Odontologos"));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Telefono", "Documento", "Correo", "Experiencia", "Salario", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setDragEnabled(true);
        jScrollPane2.setViewportView(jTable1);

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2))
        );

        javax.swing.GroupLayout jPnl_ListarLayout = new javax.swing.GroupLayout(jPnl_Listar);
        jPnl_Listar.setLayout(jPnl_ListarLayout);
        jPnl_ListarLayout.setHorizontalGroup(
            jPnl_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnl_ListarLayout.setVerticalGroup(
            jPnl_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPnl_Listar);

        jMenu1.setText("Archivo");

        jMPrincipal.setText("Menu Principal");
        jMenu1.add(jMPrincipal);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMSalir);

        jmenu_principal.add(jMenu1);

        setJMenuBar(jmenu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftxf_Apellidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxf_Apellidos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxf_Apellidos1ActionPerformed

    private void jBtn_Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Guardar1ActionPerformed
        // TODO add your handling code here:
        
        try {
            if(validarDatosEditar()){
                String Nombres = jftxtf_Nombres1.getText();
                String Apellidos = jftxf_Apellidos1.getText();
                long Numero_Documento = Long.parseLong(jftxtf_N_Documento1.getText());
                long Telefono = Long.parseLong(jftxtf_Telefono1.getText());
                String Correo = jftxtf_Correo1.getText();
                String Direccion = jftxtf_Direccion1.getText(); 
                int Experiencia = (int) jSpn_Edit_Experiencia.getValue();
                double Salario = Double.parseDouble(jftxtf_Salario1.getText());
                 
                Odontologos od = new Odontologos();
                od.Editar(this.idTempo, Nombres, Apellidos, Numero_Documento, Telefono, Correo, Direccion, Experiencia, Salario);
                cargarListaOdontologos(jComboBox1);
            }
        }catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, "Error al ingresar datos "+ne, "Datos No Validos", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error General Editar"+e, "Datos No Validos ", JOptionPane.ERROR_MESSAGE);
        }
                
    }//GEN-LAST:event_jBtn_Guardar1ActionPerformed

    private void jBtn_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Cancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_Cancelar1ActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        cargarListaOdontologos(jComboBox1);
        cargarListaOdontologos(jCbx_Eliminar_Odontologo);
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jPnl_EditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPnl_EditarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnl_EditarFocusGained

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        try {
            Odontologos Odontologo = (Odontologos) jComboBox1.getSelectedItem();
            jftxtf_Nombres1.setText(Odontologo.getNombres());
            jftxf_Apellidos1.setText(Odontologo.getApellidos());
            jftxtf_Telefono1.setText(String.valueOf(Odontologo.getTelefono()));
            jftxtf_N_Documento1.setText(String.valueOf(Odontologo.getN_Documento()));
            jftxtf_Correo1.setText(String.valueOf(Odontologo.getCorreo()));
            jSpn_Edit_Experiencia.setValue(Odontologo.getTiempo_Experiencia());
            jftxtf_Salario1.setText(String.valueOf(Odontologo.getSalario()));
            jftxtf_Direccion1.setText(String.valueOf(Odontologo.getDireccion()));
            this.idTempo = Odontologo.getId();
            jPanel_Edit_Odontologo.setVisible(true);
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Campo = jcb_Buscar_Campo.getSelectedItem().toString();
        String Termino = jTxt_Busqueda_Basica.getText();
        Odontologos od = new Odontologos();
        ArrayList<Odontologos> arrOdontologos = new ArrayList<Odontologos>();
        arrOdontologos = od.Buscar(this.formarWhere(Campo, Termino));
        listOdontologosTabla(arrOdontologos, jTbl_Buscar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CancelarActionPerformed
        // TODO add your handling code here:
        limpiarCamposfrmNew();
    }//GEN-LAST:event_jBtn_CancelarActionPerformed

    private void jBtn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_GuardarActionPerformed
        // TODO add your handling code here:
        try {
            if(validarDatos()){
                String Nombres = jftxtf_Nombres.getText();
                String Apellidos = jftxf_Apellidos.getText();
                long Numero_Documento = Long.parseLong(jftxtf_N_Documento.getText());
                long Telefono = Long.parseLong(jftxtf_Telefono.getText());
                String Correo = jftxtf_Correo.getText();
                String Direccion = jftxtf_Direccion.getText();
                int Experiencia = (int) jSpn_Experiencia.getValue();
                double Salario = Double.parseDouble(jftxtf_Salario.getText());

                Odontologos od = new Odontologos();
                if(od.Nuevo(Nombres, Apellidos, Numero_Documento, Telefono, Correo, Direccion, Experiencia, Salario)){
                    JOptionPane.showMessageDialog(rootPane, "Odontolog Creado Con Exito", "Creacion de Odontologo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch (NumberFormatException ne) {
            JOptionPane.showMessageDialog(rootPane, "Error al ingresar datos "+ne, "Datos No Validos", JOptionPane.ERROR_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error General "+e, "Datos No Validos ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_GuardarActionPerformed

    private void jftxf_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftxf_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftxf_ApellidosActionPerformed

    private void jBtn_Cancelar_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Cancelar_EliminarActionPerformed
        // TODO add your handling code here:
        limpiarCamposfrmEdit();
        this.idTempoEliminar = 0;
    }//GEN-LAST:event_jBtn_Cancelar_EliminarActionPerformed

    private void jBtn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_EliminarActionPerformed
        // TODO add your handling code here:
        if (this.idTempoEliminar != 0){
            int confirmado = JOptionPane.showConfirmDialog(this, "¿Deseas Realmente Eliminar el Odontologo?","Eliminar Odontologo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (JOptionPane.YES_OPTION == confirmado){
                Odontologos odTemp = new Odontologos();
                if(odTemp.Eliminar(idTempoEliminar)){
                    JOptionPane.showMessageDialog(rootPane, "El Odontologo se ha eliminado correctamente de la base de datos", "Eliminar Odontologo", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCamposfrmEdit();
                    cargarListaOdontologos(jCbx_Eliminar_Odontologo);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "NO se ha podido eliminar el usuario", "Error Eliminar Odontologo", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Operacion Cancelada", "Eliminar Odontologo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBtn_EliminarActionPerformed

    private void jCbx_Eliminar_OdontologoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbx_Eliminar_OdontologoItemStateChanged
        // TODO add your handling code here:

        try {
            Odontologos Odontologo = (Odontologos) jCbx_Eliminar_Odontologo.getSelectedItem();
            jTxtf_Nombres_Eliminar.setText(Odontologo.getNombres());
            jTxtf_Apellidos_Eliminar.setText(Odontologo.getApellidos());
            jTxtf_Telefono_Eliminar.setText(String.valueOf(Odontologo.getTelefono()));
            jTxtf_Documento_Eliminar.setText(String.valueOf(Odontologo.getN_Documento()));
            jTxtf_Correo_Eliminar.setText(String.valueOf(Odontologo.getCorreo()));
            jTxtf_Experiencia_Eliminar.setText(String.valueOf(Odontologo.getTiempo_Experiencia()));
            jTxtf_Salario_Eliminar.setText(String.valueOf(Odontologo.getSalario()));
            jTxtf_Direccion_Eliminar.setText(String.valueOf(Odontologo.getDireccion()));
            this.idTempoEliminar = Odontologo.getId();
            jPanel_Deleted_Odontologo.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jCbx_Eliminar_OdontologoItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ListarOdontologos();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public String formarWhere (String Campo, String Valor){
        String Where = "1";       
        if (Campo.equalsIgnoreCase("Nombres")){
            Where = "NOMBRES LIKE '%"+Valor+"%'";
        }else if (Campo.equalsIgnoreCase("Apellidos")){
            Where = "APELLIDOS LIKE '%"+Valor+"%'";
        }else if (Campo.equalsIgnoreCase("Telefono")){
            Where = "TELEFONO = "+Valor+"";
        }else if (Campo.equalsIgnoreCase("Identificacion")){
            Where = "NUMERODEDOCUMENTO = "+Valor+"";
        }else if (Campo.equalsIgnoreCase("Correo")){
            Where = "CORREOELECTRONICO LIKE '%"+Valor+"%'";
        }else if (Campo.equalsIgnoreCase("Tiempo Experiencia")){
            Where = "TIEMPODEEXPERIECIA = "+Valor+"";
        }else if (Campo.equalsIgnoreCase("Salario")){
            Where = "SALARIO = "+Valor+"";
        }else if (Campo.equalsIgnoreCase("Direccion")){
            Where = "DIRECCION = "+Valor+"";
        }
        return Where;
    }
    
    public void listOdontologosTabla (ArrayList<Odontologos> arrOdontologos, JTable tabla){
        
        DefaultTableModel modelBase = (DefaultTableModel) tabla.getModel();
        modelBase = limpiarTabla(modelBase);
        for (Odontologos odonto : arrOdontologos) {
            Vector tempOdonto = new Vector();
            tempOdonto.add(odonto.getNombres());
            tempOdonto.add(odonto.getApellidos());
            tempOdonto.add(odonto.getTelefono());
            tempOdonto.add(odonto.getN_Documento());
            tempOdonto.add(odonto.getCorreo());
            tempOdonto.add(odonto.getTiempo_Experiencia());
            tempOdonto.add(odonto.getSalario());
            tempOdonto.add(odonto.getDireccion());
            modelBase.addRow(tempOdonto);
        }
        tabla.setModel(modelBase);

    }
    
    public DefaultTableModel limpiarTabla (DefaultTableModel model){
        int filas = model.getRowCount();
        for (int i = 0;i<filas; i++) {
            model.removeRow(0); //Eliminacion en pila.
        }
        return model;
    }
    
    
    private boolean validarDatos (){
       
        if(jftxf_Apellidos.getText().isEmpty() || jftxtf_Correo.getText().isEmpty() || jftxtf_Direccion.getText().isEmpty() ||  jftxtf_N_Documento.getText().isEmpty() || jftxtf_Nombres.getText().isEmpty() || jftxtf_Salario.getText().isEmpty() || jftxtf_Telefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Se deben de ingresar todos los campos", "Datos No Validos", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }

    private boolean validarDatosEditar (){
       
        if(jftxf_Apellidos1.getText().isEmpty() || jftxtf_Correo1.getText().isEmpty() || jftxtf_Direccion1.getText().isEmpty() || jftxtf_N_Documento1.getText().isEmpty() || jftxtf_Nombres1.getText().isEmpty() || jftxtf_Salario1.getText().isEmpty() || jftxtf_Telefono1.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Se deben de ingresar todos los campos", "Datos No Validos", JOptionPane.ERROR_MESSAGE);
            return false;
        }else{
            return true;
        }
    }
    
    public void limpiarCamposfrmNew(){
        jftxf_Apellidos.setText("");
        jftxtf_Correo.setText("");
        jftxtf_Direccion.setText("");
        jSpn_Experiencia.setValue(1);
        jftxtf_N_Documento.setText("");
        jftxtf_Nombres.setText("");
        jftxtf_Salario.setText("");
        jftxtf_Telefono.setText("");
    }
    
    public void limpiarCamposfrmEdit(){
        jTxtf_Nombres_Eliminar.setText("");
        jTxtf_Apellidos_Eliminar.setText("");
        jTxtf_Telefono_Eliminar.setText("");
        jTxtf_Documento_Eliminar.setText("");
        jTxtf_Correo_Eliminar.setText("");
        jTxtf_Experiencia_Eliminar.setText("");
        jTxtf_Salario_Eliminar.setText("");
        jTxtf_Direccion_Eliminar.setText("");
    }
    
    public static void cargarListaOdontologos(JComboBox combo){
        combo.removeAllItems();
        ArrayList <Odontologos> listOdontologos;
        Odontologos odonto = new Odontologos();
        listOdontologos = odonto.Buscar("1");
        for (Odontologos odo : listOdontologos) {
            combo.addItem(odo);
        }
    }

    public static void cargarListaOdontologos(JComboBox combo, int Id){
        combo.removeAllItems();
        ArrayList <Odontologos> listOdontologos;
        Odontologos odonto = new Odontologos();
        listOdontologos = odonto.Buscar("1");
        for (Odontologos odo : listOdontologos) {
            combo.addItem(odo);
            if(odo.getId() == Id){
                combo.setSelectedItem(odo);
            }
        }
    }
    
    public void ListarOdontologos(){
        ArrayList <Odontologos> listOdontologos;
        Odontologos odonto = new Odontologos();
        listOdontologos = odonto.Buscar("1");
        listOdontologosTabla(listOdontologos,jTable1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOdontologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOdontologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOdontologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOdontologos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOdontologos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Cancelar;
    private javax.swing.JButton jBtn_Cancelar1;
    private javax.swing.JButton jBtn_Cancelar_Eliminar;
    private javax.swing.JButton jBtn_Eliminar;
    private javax.swing.JButton jBtn_Guardar;
    private javax.swing.JButton jBtn_Guardar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbx_Eliminar_Odontologo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbl_Apellidos;
    private javax.swing.JLabel jLbl_Apellidos1;
    private javax.swing.JLabel jLbl_Direccion;
    private javax.swing.JLabel jLbl_Direccion1;
    private javax.swing.JLabel jLbl_Experiencia;
    private javax.swing.JLabel jLbl_Experiencia1;
    private javax.swing.JLabel jLbl_Nombres;
    private javax.swing.JLabel jLbl_Nombres1;
    private javax.swing.JLabel jLbl_Numero_Documento;
    private javax.swing.JLabel jLbl_Numero_Documento1;
    private javax.swing.JLabel jLbl_Salario;
    private javax.swing.JLabel jLbl_Salario1;
    private javax.swing.JLabel jLbl_Telefono;
    private javax.swing.JLabel jLbl_Telefono1;
    private javax.swing.JMenuItem jMPrincipal;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Deleted_Odontologo;
    private javax.swing.JPanel jPanel_Edit_Odontologo;
    private javax.swing.JPanel jPnEliminar;
    private javax.swing.JPanel jPnlBusq_Basica;
    private javax.swing.JPanel jPnl_Buscar;
    private javax.swing.JPanel jPnl_Editar;
    private javax.swing.JPanel jPnl_Eliminar;
    private javax.swing.JPanel jPnl_Listar;
    private javax.swing.JPanel jPnl_Nuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpn_Edit_Experiencia;
    private javax.swing.JSpinner jSpn_Experiencia;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTbl_Buscar;
    private javax.swing.JTextField jTxt_Busqueda_Basica;
    private javax.swing.JTextField jTxtf_Apellidos_Eliminar;
    private javax.swing.JTextField jTxtf_Correo_Eliminar;
    private javax.swing.JTextField jTxtf_Direccion_Eliminar;
    private javax.swing.JTextField jTxtf_Documento_Eliminar;
    private javax.swing.JTextField jTxtf_Experiencia_Eliminar;
    private javax.swing.JTextField jTxtf_Nombres_Eliminar;
    private javax.swing.JTextField jTxtf_Salario_Eliminar;
    private javax.swing.JTextField jTxtf_Telefono_Eliminar;
    private javax.swing.JComboBox jcb_Buscar_Campo;
    private javax.swing.JFormattedTextField jftxf_Apellidos;
    private javax.swing.JFormattedTextField jftxf_Apellidos1;
    private javax.swing.JFormattedTextField jftxtf_Correo;
    private javax.swing.JFormattedTextField jftxtf_Correo1;
    private javax.swing.JFormattedTextField jftxtf_Direccion;
    private javax.swing.JFormattedTextField jftxtf_Direccion1;
    private javax.swing.JFormattedTextField jftxtf_N_Documento;
    private javax.swing.JFormattedTextField jftxtf_N_Documento1;
    private javax.swing.JFormattedTextField jftxtf_Nombres;
    private javax.swing.JFormattedTextField jftxtf_Nombres1;
    private javax.swing.JFormattedTextField jftxtf_Salario;
    private javax.swing.JFormattedTextField jftxtf_Salario1;
    private javax.swing.JFormattedTextField jftxtf_Telefono;
    private javax.swing.JFormattedTextField jftxtf_Telefono1;
    private javax.swing.JMenuBar jmenu_principal;
    // End of variables declaration//GEN-END:variables
}
